---
runtime:
  threads: ~
release:
  check: true
manifest:
  enable: true
language: it-IT
theme: dark
roots:
  - store: steam
    path: "C:/Program Files (x86)/Steam"
  - store: epic
    path: "C:/Program Files (x86)/Epic Games"
  - store: epic
    path: "C:/Program Files/Epic Games"
  - store: microsoft
    path: "C:/Program Files/WindowsApps"
  - store: ea
    path: "C:/Program Files/EA Games"
  - store: steam
    path: "D:/SteamLibrary"
  - store: other
    path: "C:/Users/paffe/OneDrive/Documenten/rpcs3-v0.0.38-18540-f946054a_win64_msvc/dev_hdd0/home"
redirects: []
backup:
  path: "D:/Backup Save Data"
  ignoredGames:
    - The Sea Between
  filter:
    excludeStoreScreenshots: false
    cloud:
      exclude: false
      epic: false
      gog: false
      origin: false
      steam: false
      uplay: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths:
    The Sea Between:
      "C:/Users/paffe/AppData/Local/User Data": false
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
  onlyConstructive: false
restore:
  path: "D:/Backup Save Data"
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  reverseRedirects: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote: ~
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: ""
    arguments: "--fast-list --ignore-checksum"
customGames:
- name: "Catherine (Sony PlayStation 3)"
  integration: override
  files:
    - "C:/Users/paffe/OneDrive/Documenten/rpcs3-v0.0.38-18540-f946054a_win64_msvc/dev_hdd0/home/00000001/savedata/BLES01459-00-FIXED-"
  registry: []
  installDir: []
  winePrefix: []
- name: "Phoenix Wright - Ace Attorney - Justice for All (Nintendo DS - MelonDS)"
  integration: override
  files:
    - "C:/Users/paffe/OneDrive/Documenten/Playnite Roms/Phoenix Wright - Ace Attorney - Justice for All (Europe) (Es,It).sav"
  registry: []
  installDir: []
  winePrefix: []
